server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://ep-muddy-snow-a7mmx194-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sLrezEl4kq5C
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret="${JWT_SECRET}"
jwt.access-expiration=1800000
jwt.refresh-expiration=2592000000